name: production
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t tooler:latest .

  kill:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Kill
        run: docker kill tooler

  remove:
    runs-on: self-hosted
    needs: [kill]
    continue-on-error: true
    steps:
      - name: Remove
        run: docker rm tooler

  run:
    runs-on: self-hosted
    needs: [build, remove]
    steps:
      - name: Run
        run: docker run --name tooler tooler

  # clean:
  #   runs-on: self-hosted
  #   needs: [run]
  #   steps:
  #     - name: Clean Docker After Run
  #       run: docker system prune -af --volumes
