name: production
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t tooler:latest .

  run:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Run
        run: docker run --rm --name tooler tooler

  clean:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Clean Docker After Run
        run: docker image prune
